// Code generated by mockery v1.0.0
package mocks

import entity "github.com/asiragusa/wschat/entity"
import mock "github.com/stretchr/testify/mock"

// PubsubClient is an autogenerated mock type for the PubsubClient type
type PubsubClient struct {
	mock.Mock
}

// Publish provides a mock function with given fields: _a0
func (_m *PubsubClient) Publish(_a0 entity.Message) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(entity.Message) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Subscribe provides a mock function with given fields: _a0, _a1
func (_m *PubsubClient) Subscribe(_a0 string, _a1 func(entity.Message)) (error, func()) {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, func(entity.Message)) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	var r1 func()
	if rf, ok := ret.Get(1).(func(string, func(entity.Message)) func()); ok {
		r1 = rf(_a0, _a1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(func())
		}
	}

	return r0, r1
}
