// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"
import response "github.com/asiragusa/wschat/response"

// RequestValidator is an autogenerated mock type for the RequestValidator type
type RequestValidator struct {
	mock.Mock
}

// FormatError provides a mock function with given fields: _a0
func (_m *RequestValidator) FormatError(_a0 interface{}) response.Response {
	ret := _m.Called(_a0)

	var r0 response.Response
	if rf, ok := ret.Get(0).(func(interface{}) response.Response); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(response.Response)
		}
	}

	return r0
}

// Struct provides a mock function with given fields: _a0
func (_m *RequestValidator) Struct(_a0 interface{}) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
