// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"
import request "github.com/asiragusa/wschat/request"
import response "github.com/asiragusa/wschat/response"

// WsTokenInteractor is an autogenerated mock type for the WsTokenInteractor type
type WsTokenInteractor struct {
	mock.Mock
}

// Call provides a mock function with given fields: _a0
func (_m *WsTokenInteractor) Call(_a0 request.CreateWsToken) response.Response {
	ret := _m.Called(_a0)

	var r0 response.Response
	if rf, ok := ret.Get(0).(func(request.CreateWsToken) response.Response); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(response.Response)
		}
	}

	return r0
}
